region = "eu-west-3"
instance_ami_polybot = "ami-00ac45f3035ff009e"
key_pair_name_polybot = "galgu-Paris-Key"
instance_type_polybot = "t2.micro"
availability_zones = ["eu-west-3a", "eu-west-3b"]
vpc_azs = ["eu-west-3a", "eu-west-3b"]
instance_ami_yolo5 = "ami-09d83d8d719da9808"
instance_type_yolo5 = "t2.medium"
key_pair_name_yolo5 = "galgu-Paris-Key"
lb_target_group_arn = ""