name: Polybot Infrastructure Terraform Main

on:
  workflow_dispatch:
    inputs:
      us-east-2:
        description: 'Ohio (us-east-2)'
        required: false
        type: boolean
      eu-west-3:
        description: 'Paris (eu-west-3)'
        required: false
        type: boolean

jobs:
  us-east-2:
    if: ${{ github.event.inputs.us-east-2 == 'true' }}
    uses: ./.github/workflows/infra-provisioning-region.yaml
    with:
      region-code: us-east-2
    secrets:
      TELEGRAM_TOKEN: ${{ secrets.US_EAST_2_TELEGRAM_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.US_EAST_2_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.US_EAST_2_AWS_SECRET_ACCESS_KEY }}

  eu-west-3:
    if: ${{ github.event.inputs.eu-west-3 == 'true' }}
    uses: ./.github/workflows/infra-provisioning-region.yaml
    with:
      region-code: eu-west-3
    secrets:
      TELEGRAM_TOKEN: ${{ secrets.EU_WEST_3_TELEGRAM_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.EU_WEST_3_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.EU_WEST_3_AWS_SECRET_ACCESS_KEY }}